package com.javarush.task.task04.task0418;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
/*                                                                                                                                                                                                                                                                                                                                                               
Минимум двух чисел                                                                                                                                                                                                                                                                                                                                                              
*/                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
import java.io.*;                                                                                                                                                                                                                                                                                                                                                              
import java.util.*;                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                              
public class Solution {                                                                                                                                                                                                                                                                                                                                                              
    public static void main(String[] args) throws Exception {                                                                                                                                                                                                                                                                                                                                                              
        //напишите тут ваш код                                                                                                                                                                                                                                                                                                                                                              
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));                                                                                                                                                                                                        
        int a = Integer.parseInt(reader.readLine());                                                                                                                                                                                                        
        int b = Integer.parseInt(reader.readLine());                                                                                                                                                                                                        
                                                                                                                                                                                                                
        int c;                                                                                                                                                                                                            
        if (a < b)                                                                                                                                                                                                        
            c = a;                                                                                                                                                                                                        
        else if (a > b)                                                                                                                                                                                                       
            c = b;
        else
            c = a;                                                                                                                                                                                                        
                                                                                                                                                                                                                
        System.out.println(c);                                                                                                                                                                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                                                                                                                                              
}